### ISSUE TITLE
import 'cypress-mailosaur' doesn't work with Cypress 5.1.0

### ISSUE THREAD

**Issue by gustawx** [mailosaur/cypress-mailosaur#6]
After including `import 'cypress-mailosaur'` in commands.ts file I get following error:

`Property 'mailosaurGetMessage' does not exist on type 'cy & EventEmitter'`

for following code:
`cy.mailosaurGetMessage(Cypress.env('MAILOSAUR_SERVERID')`

Cypress version 5.1.0

**Comment by hippyhorse** [comment]
Just to close this out, we looked into this and were unable to reproduce using v5.1.0. If you are still experiencing this, please do contact us at support@mailosaur.com
